name: build database

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup git config
        run: git config user.name "GitHub Actions Bot" user.email "<>"

      - name: generate database
        run: make clean && make release
