name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_database:
    needs: [create_release]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: generate database
        run: make

      - name: get latest release
        id: latest_release_info
        uses: jossef/action-latest-release-info@v1.1.0

      - name: upload database
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
          asset_path: ./kiss-find.gz
          asset_name: kiss-find.gz
          asset_content_type: application/gzip
