name: build database

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update_database:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: generate database
        run: make

      - name: recreate release
        id: recreate_release
        uses: GongT/actions-recreate-release@v1
        with:
          tag_name: latest
          release_name: Release at ${{ github.sha }}
          draft: false
          prerelease: false

      - name: upload database
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.recreate_release.outputs.upload_url }}
          asset_path: ./build/db
          asset_name: db
          asset_content_type: text/csv
