name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    needs: [create_release]
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: generate database
        run: make

      - name: upload database
        uses: skx/github-action-publish-binaries@release-0.14
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: kiss-find.gz
