name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "0 */6 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v2

      - name: generate database
        run: |
          echo gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
          make

      - name: upload database
        uses: skx/github-action-publish-binaries@release-0.14
        with:
          args: kiss-find.gz
          
